# optional
# copies: 0-N
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ .metadata.name }} #$name
  namespace: {{ .metadata.namespace }} #$ns
spec:
  {{ if .spec.nodeSelector }}
  nodeSelector:
    {{ .spec.nodeSelector | toYaml | indent 4 }}
  {{ end }}
  config: {{ .spec.config }} #$config
  #eg
  #config: '{
  #  "cniVersion": "0.3.1",
  #  "name": "external-169",
  #  "type": "vlan",
  #  "master": "ens8f0",
  #  "mode": "bridge",
  #  "vlanid": 169,
  #  "ipam": {
  #    "type": "static",
  #  }
  #}'