apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
# Use PolicyGenerator to create oadp cm and ibu policies
- acm-pg-ran-ibu-upgrade.yaml
# Legacy (deprecated): use policygentemplate to create oadp cm and ibu policies
# - pgt-ibu-upgrade.yaml

# This patch should be removed once the legacy pgt-ibu-upgrade.yaml (PolicyGenTemplate) is fully removed
patches:
- target:
    group: policy.open-cluster-management.io
    version: v1
    kind: Policy
    name: group-ibu-oadp-cm-policy
  patch: |-
    - op: replace
      path: /spec/policy-templates/0/objectDefinition/spec/object-templates/0/objectDefinition/data
      value: '{{hub copyConfigMapData "ztp-group" "oadp-cm" hub}}'

configMapGenerator:
- files:
  - ../../reference-crs/ibu/PlatformBackupRestore.yaml
  # - <add-workload-oadp-crs-here>
  name: oadp-cm
  namespace: ztp-group

generatorOptions:
  disableNameSuffixHash: true
