apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
metadata:
  name: vewl-localnet1 
spec:
  namespaceSelector: 
    matchLabels:
      vewl-network: "true"
  network:
    topology: Localnet 
    localnet:
        role: Secondary 
        physicalNetworkName: localnet1 
        vlan:
          mode: Access
          access:
            id: 64
        ipam:
          mode: Disabled