---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../other-crs/required/quay/

patches:
  - target:
      group: external-secrets.io
      version: v1
      kind: ExternalSecret
      name: quay-config-bundle-secret
    path: quay_secret-patch.yaml
