# required
# count: 1
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: {{ .metadata.name }}
spec:
#  repositoryDigestMirrors: # []
{{ if .spec.repositoryDigestMirrors }}
  repositoryDigestMirrors: # []
#    - $mirrors
{{ .spec.repositoryDigestMirrors | toYaml | indent 2 }}
{{end}}


