---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generators:
- mgmt-baseline.yaml
- mgmt-odf-external.yaml
- mgmt-odf-internal.yaml
- mgmt-lvms.yaml
- mgmt-kafka.yaml
- mgmt-auth-idm.yaml
- mgmt-quay.yaml
- mgmt-ztp.yaml
- mgmt-optional.yaml
- mgmt-finish.yaml
- mgmt-ztp-upgrade-21.yaml
- mgmt-ztp-upgrade-22.yaml
- mgmt-ztp-upgrade-finish.yaml
resources:
- clusterimageset.yaml
- resources
- template-values/mgmt1.yaml
