---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generators:
- mgmt-baseline.yaml
- mgmt-odf-external.yaml
- mgmt-odf-internal.yaml
- mgmt-lvms.yaml
- mgmt-kafka.yaml
- mgmt-auth-idm.yaml
- mgmt-quay.yaml
- mgmt-ztp.yaml
- mgmt-optional.yaml
- mgmt-finish.yaml
resources:
- clusterimageset42016.yaml
- resources
- template-values/mgmt1.yaml
