---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ansible-automation-platform
  namespace: ansible-automation-platform
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
spec:
  channel: 'stable-2.6'
  installPlanApproval: Automatic
  name: ansible-automation-platform-operator
  source: redhat-operators-disconnected
  sourceNamespace: openshift-marketplace

