---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rhsoso-ceph
  namespace: openstack
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: $path_to_secret_vault
      metadataPolicy: None
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: rhoso-ceph
