apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  labels:
    machineconfiguration.openshift.io/role: workload-3-worker-mcp
  name: workload-3-worker-mcp
spec:
  machineConfigSelector:
    matchExpressions:
    - key: machineconfiguration.openshift.io/role
      operator: In
      values:
      - workload-3-worker-mcp
      - worker
  # installation paused
  # installation will be done at the end of ZTP
  paused: true
  # example (default) 1 node unavailable during deployment
  maxUnavailable: 1
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/workload-3-worker-mcp: ""
