apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 75-sshd-permit-empty-passwords-worker
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  config:
    ignition:
      version: 3.5.0
    storage:
      files:
        - path: /etc/ssh/sshd_config.d/01-permit-empty-passwords.conf
          mode: 0600
          overwrite: true
          contents:
            source: "data:,PermitEmptyPasswords%20no%0A"
