# Combined from the following remediations for /etc/ssh/sshd_config (all roles):
#   - rhcos4-e8-worker-sshd-disable-rhosts.yaml
#   - rhcos4-e8-worker-sshd-disable-root-login.yaml
#   - rhcos4-e8-master-sshd-enable-strictmodes.yaml
#   - rhcos4-e8-master-sshd-set-loglevel-info.yaml
#   - rhcos4-e8-worker-sshd-disable-gssapi-auth.yaml
#   - rhcos4-e8-master-sshd-disable-user-known-hosts.yaml
#   - rhcos4-e8-master-sshd-disable-empty-passwords.yaml
#   - rhcos4-e8-worker-sshd-disable-user-known-hosts.yaml
#   - rhcos4-e8-worker-sshd-print-last-log.yaml
#   - rhcos4-e8-master-sshd-do-not-permit-user-env.yaml
#   - rhcos4-e8-worker-sshd-set-loglevel-info.yaml
#   - rhcos4-e8-master-sshd-disable-gssapi-auth.yaml
#   - rhcos4-e8-master-sshd-disable-root-login.yaml
#   - rhcos4-e8-worker-sshd-enable-strictmodes.yaml
#   - rhcos4-e8-master-sshd-disable-rhosts.yaml
#   - rhcos4-e8-worker-sshd-disable-empty-passwords.yaml
#   - rhcos4-e8-master-sshd-print-last-log.yaml
#   - rhcos4-e8-worker-sshd-do-not-permit-user-env.yaml
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
        - contents:
            # The following lines are the deduplicated, combined plaintext contents from all related MachineConfig remediations.
            # #
            # #	$OpenBSD: sshd_config,v 1.103 2018/04/09 20:41:22 tj Exp $
            # #	AllowTcpForwarding no
            # #	ForceCommand cvs server
            # #	PermitTTY no
            # #	X11Forwarding no
            # # Accept locale-related environment variables
            # # Authentication:
            # # Change to no to disable s/key passwords
            # # Change to yes if you don't trust ~/.ssh/known_hosts for
            # # Ciphers and keying
            # # Ciphers, MACs, KexAlgoritms and GSSAPIKexAlgorithsm will not have any
            # # Don't read the user's ~/.rhosts and ~/.shosts files
            # # Example of overriding settings on a per-user basis
            # # For more information, see manual page for update-crypto-policies(8).
            # # For this to work you will also need host keys in /etc/ssh/ssh_known_hosts
            # # GSSAPI options
            # # HostbasedAuthentication
            # # If you just want the PAM account and session checks to run without
            # # If you want to change the port on a SELinux system, you have to tell
            # # It is recommended to use pam_motd in /etc/pam.d/sshd instead of PrintMotd,
            # # Kerberos options
            # # Logging
            # # OpenSSH is to specify options with their default value where
            # # PAM authentication via ChallengeResponseAuthentication may bypass
            # # PAM authentication, then enable this but set PasswordAuthentication
            # # PasswordAuthentication.  Depending on your PAM configuration,
            # # SELinux about this change.
            # # Set this to 'yes' to enable PAM authentication, account processing,
            # # System-wide Crypto policy:
            # # The default is to check both .ssh/authorized_keys and .ssh/authorized_keys2
            # # The strategy used for options in the default sshd_config shipped with
            # # This is the sshd server system-wide configuration file.  See
            # # This sshd was compiled with PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
            # # This system is following system-wide crypto policy. The changes to
            # # To disable tunneled clear text passwords, change to no here!
            # # To opt out, uncomment a line with redefinition of  CRYPTO_POLICY=
            # # WARNING: 'UsePAM no' is not supported in Fedora and may cause several
            # # and ChallengeResponseAuthentication to 'no'.
            # # and session processing. If this is enabled, PAM authentication will
            # # as it is more configurable and versatile than the built-in version.
            # # be allowed through the ChallengeResponseAuthentication and
            # # but this is overridden so installations will only check .ssh/authorized_keys
            # # default value.
            # # effect here. They will be overridden by command-line options passed on
            # # no default banner path
            # # override default of no subsystems
            # # possible, but leave them commented.  Uncommented options override the
            # # problems.
            # # semanage port -a -t ssh_port_t -p tcp #PORTNUMBER
            # # sshd_config(5) for more information.
            # # the server start up.
            # # the setting of "PermitRootLogin without-password".
            # # variable in  /etc/sysconfig/sshd  to overwrite the policy.
            # #AddressFamily any
            # #AllowAgentForwarding yes
            # #AllowTcpForwarding yes
            # #AuthorizedKeysCommand none
            # #AuthorizedKeysCommandUser nobody
            # #AuthorizedPrincipalsFile none
            # #ChallengeResponseAuthentication yes
            # #ChrootDirectory none
            # #GSSAPIEnablek5users no
            # #GSSAPIKeyExchange no
            # #GSSAPIStrictAcceptorCheck yes
            # #GatewayPorts no
            # #KerberosGetAFSToken no
            # #KerberosOrLocalPasswd yes
            # #KerberosTicketCleanup yes
            # #KerberosUseKuserok yes
            # #ListenAddress 0.0.0.0
            # #ListenAddress ::
            # #LoginGraceTime 60
            # #Match User anoncvs
            # #MaxAuthTries 6
            # #MaxSessions 10
            # #MaxStartups 10:30:100
            # #PasswordAuthentication yes
            # #PermitTTY yes
            # #PermitTunnel no
            # #PidFile /var/run/sshd.pid
            # #Port 22
            # #SyslogFacility AUTH
            # #TCPKeepAlive yes
            # #UseDNS no
            # #VersionAddendum none
            # #X11DisplayOffset 10
            # #X11UseLocalhost yes
            # AcceptEnv LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES
            # AcceptEnv LC_IDENTIFICATION LC_ALL LANGUAGE
            # AcceptEnv LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT
            # AcceptEnv XMODIFIERS
            # AuthorizedKeysFile	.ssh/authorized_keys
            # Banner /etc/issue
            # ChallengeResponseAuthentication no
            # ClientAliveCountMax 0
            # ClientAliveInterval 300
            # Compression no
            # GSSAPIAuthentication no
            # GSSAPICleanupCredentials no
            # HostKey /etc/ssh/ssh_host_ecdsa_key
            # HostKey /etc/ssh/ssh_host_ed25519_key
            # HostKey /etc/ssh/ssh_host_rsa_key
            # HostbasedAuthentication no
            # IgnoreRhosts yes
            # IgnoreUserKnownHosts yes
            # Include /etc/ssh/sshd_config.d/*.conf
            # KerberosAuthentication no
            # LogLevel INFO
            # PasswordAuthentication no
            # PermitEmptyPasswords no
            # PermitRootLogin no
            # PermitUserEnvironment no
            # PrintLastLog yes
            # PrintMotd no
            # PubkeyAuthentication yes
            # RekeyLimit 512M 1h
            # StrictModes yes
            # Subsystem	sftp	/usr/libexec/openssh/sftp-server
            # SyslogFacility AUTHPRIV
            # UsePAM yes
            # UsePrivilegeSeparation sandbox
            # X11Forwarding yes
            source: data:,%23%0A%23%09%24OpenBSD%3A%20sshd_config%2Cv%201.103%202018%2F04%2F09%2020%3A41%3A22%20tj%20Exp%20%24%0A%23%09AllowTcpForwarding%20no%0A%23%09ForceCommand%20cvs%20server%0A%23%09PermitTTY%20no%0A%23%09X11Forwarding%20no%0A%23%20Accept%20locale-related%20environment%20variables%0A%23%20Authentication%3A%0A%23%20Change%20to%20no%20to%20disable%20s%2Fkey%20passwords%0A%23%20Change%20to%20yes%20if%20you%20don%27t%20trust%20~%2F.ssh%2Fknown_hosts%20for%0A%23%20Ciphers%20and%20keying%0A%23%20Ciphers%2C%20MACs%2C%20KexAlgoritms%20and%20GSSAPIKexAlgorithsm%20will%20not%20have%20any%0A%23%20Don%27t%20read%20the%20user%27s%20~%2F.rhosts%20and%20~%2F.shosts%20files%0A%23%20Example%20of%20overriding%20settings%20on%20a%20per-user%20basis%0A%23%20For%20more%20information%2C%20see%20manual%20page%20for%20update-crypto-policies%288%29.%0A%23%20For%20this%20to%20work%20you%20will%20also%20need%20host%20keys%20in%20%2Fetc%2Fssh%2Fssh_known_hosts%0A%23%20GSSAPI%20options%0A%23%20HostbasedAuthentication%0A%23%20If%20you%20just%20want%20the%20PAM%20account%20and%20session%20checks%20to%20run%20without%0A%23%20If%20you%20want%20to%20change%20the%20port%20on%20a%20SELinux%20system%2C%20you%20have%20to%20tell%0A%23%20It%20is%20recommended%20to%20use%20pam_motd%20in%20%2Fetc%2Fpam.d%2Fsshd%20instead%20of%20PrintMotd%2C%0A%23%20Kerberos%20options%0A%23%20Logging%0A%23%20OpenSSH%20is%20to%20specify%20options%20with%20their%20default%20value%20where%0A%23%20PAM%20authentication%20via%20ChallengeResponseAuthentication%20may%20bypass%0A%23%20PAM%20authentication%2C%20then%20enable%20this%20but%20set%20PasswordAuthentication%0A%23%20PasswordAuthentication.%20%20Depending%20on%20your%20PAM%20configuration%2C%0A%23%20SELinux%20about%20this%20change.%0A%23%20Set%20this%20to%20%27yes%27%20to%20enable%20PAM%20authentication%2C%20account%20processing%2C%0A%23%20System-wide%20Crypto%20policy%3A%0A%23%20The%20default%20is%20to%20check%20both%20.ssh%2Fauthorized_keys%20and%20.ssh%2Fauthorized_keys2%0A%23%20The%20strategy%20used%20for%20options%20in%20the%20default%20sshd_config%20shipped%20with%0A%23%20This%20is%20the%20sshd%20server%20system-wide%20configuration%20file.%20%20See%0A%23%20This%20sshd%20was%20compiled%20with%20PATH%3D%2Fusr%2Flocal%2Fbin%3A%2Fusr%2Fbin%3A%2Fusr%2Flocal%2Fsbin%3A%2Fusr%2Fsbin%0A%23%20This%20system%20is%20following%20system-wide%20crypto%20policy.%20The%20changes%20to%0A%23%20To%20disable%20tunneled%20clear%20text%20passwords%2C%20change%20to%20no%20here%21%0A%23%20To%20opt%20out%2C%20uncomment%20a%20line%20with%20redefinition%20of%20%20CRYPTO_POLICY%3D%0A%23%20WARNING%3A%20%27UsePAM%20no%27%20is%20not%20supported%20in%20Fedora%20and%20may%20cause%20several%0A%23%20and%20ChallengeResponseAuthentication%20to%20%27no%27.%0A%23%20and%20session%20processing.%20If%20this%20is%20enabled%2C%20PAM%20authentication%20will%0A%23%20as%20it%20is%20more%20configurable%20and%20versatile%20than%20the%20built-in%20version.%0A%23%20be%20allowed%20through%20the%20ChallengeResponseAuthentication%20and%0A%23%20but%20this%20is%20overridden%20so%20installations%20will%20only%20check%20.ssh%2Fauthorized_keys%0A%23%20default%20value.%0A%23%20effect%20here.%20They%20will%20be%20overridden%20by%20command-line%20options%20passed%20on%0A%23%20no%20default%20banner%20path%0A%23%20override%20default%20of%20no%20subsystems%0A%23%20possible%2C%20but%20leave%20them%20commented.%20%20Uncommented%20options%20override%20the%0A%23%20problems.%0A%23%20semanage%20port%20-a%20-t%20ssh_port_t%20-p%20tcp%20%23PORTNUMBER%0A%23%20sshd_config%285%29%20for%20more%20information.%0A%23%20the%20server%20start%20up.%0A%23%20the%20setting%20of%20%22PermitRootLogin%20without-password%22.%0A%23%20variable%20in%20%20%2Fetc%2Fsysconfig%2Fsshd%20%20to%20overwrite%20the%20policy.%0A%23AddressFamily%20any%0A%23AllowAgentForwarding%20yes%0A%23AllowTcpForwarding%20yes%0A%23AuthorizedKeysCommand%20none%0A%23AuthorizedKeysCommandUser%20nobody%0A%23AuthorizedPrincipalsFile%20none%0A%23ChallengeResponseAuthentication%20yes%0A%23ChrootDirectory%20none%0A%23GSSAPIEnablek5users%20no%0A%23GSSAPIKeyExchange%20no%0A%23GSSAPIStrictAcceptorCheck%20yes%0A%23GatewayPorts%20no%0A%23KerberosGetAFSToken%20no%0A%23KerberosOrLocalPasswd%20yes%0A%23KerberosTicketCleanup%20yes%0A%23KerberosUseKuserok%20yes%0A%23ListenAddress%200.0.0.0%0A%23ListenAddress%20%3A%3A%0A%23LoginGraceTime%2060%0A%23Match%20User%20anoncvs%0A%23MaxAuthTries%206%0A%23MaxSessions%2010%0A%23MaxStartups%2010%3A30%3A100%0A%23PasswordAuthentication%20yes%0A%23PermitTTY%20yes%0A%23PermitTunnel%20no%0A%23PidFile%20%2Fvar%2Frun%2Fsshd.pid%0A%23Port%2022%0A%23SyslogFacility%20AUTH%0A%23TCPKeepAlive%20yes%0A%23UseDNS%20no%0A%23VersionAddendum%20none%0A%23X11DisplayOffset%2010%0A%23X11UseLocalhost%20yes%0AAcceptEnv%20LANG%20LC_CTYPE%20LC_NUMERIC%20LC_TIME%20LC_COLLATE%20LC_MONETARY%20LC_MESSAGES%0AAcceptEnv%20LC_IDENTIFICATION%20LC_ALL%20LANGUAGE%0AAcceptEnv%20LC_PAPER%20LC_NAME%20LC_ADDRESS%20LC_TELEPHONE%20LC_MEASUREMENT%0AAcceptEnv%20XMODIFIERS%0AAuthorizedKeysFile%09.ssh%2Fauthorized_keys%0ABanner%20%2Fetc%2Fissue%0AChallengeResponseAuthentication%20no%0AClientAliveCountMax%200%0AClientAliveInterval%20300%0ACompression%20no%0AGSSAPIAuthentication%20no%0AGSSAPICleanupCredentials%20no%0AHostKey%20%2Fetc%2Fssh%2Fssh_host_ecdsa_key%0AHostKey%20%2Fetc%2Fssh%2Fssh_host_ed25519_key%0AHostKey%20%2Fetc%2Fssh%2Fssh_host_rsa_key%0AHostbasedAuthentication%20no%0AIgnoreRhosts%20yes%0AIgnoreUserKnownHosts%20yes%0AInclude%20%2Fetc%2Fssh%2Fsshd_config.d%2F%2A.conf%0AKerberosAuthentication%20no%0ALogLevel%20INFO%0APasswordAuthentication%20no%0APermitEmptyPasswords%20no%0APermitRootLogin%20no%0APermitUserEnvironment%20no%0APrintLastLog%20yes%0APrintMotd%20no%0APubkeyAuthentication%20yes%0ARekeyLimit%20512M%201h%0AStrictModes%20yes%0ASubsystem%09sftp%09%2Fusr%2Flibexec%2Fopenssh%2Fsftp-server%0ASyslogFacility%20AUTHPRIV%0AUsePAM%20yes%0AUsePrivilegeSeparation%20sandbox%0AX11Forwarding%20yes%0A
          mode: 384
          overwrite: true
          path: /etc/ssh/sshd_config
metadata:
  name: 75-sshd_config-combo
  labels:
    machineconfiguration.openshift.io/role: worker
