apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
spec:
  config:
    ignition:
      version: 3.5.0
    storage:
      files:
        - contents:
            # HIGH Severity SSHD Security Setting (E8/CIS):
            # Prevent SSH login with empty passwords
            # This is a critical security control that prevents brute-force
            # attacks against accounts with no password set.
            source: data:,PermitEmptyPasswords%20no%0A
          mode: 384
          overwrite: true
          path: /etc/ssh/sshd_config.d/75-security-high.conf
metadata:
  name: 75-sshd-high
  labels:
    machineconfiguration.openshift.io/role: worker
