# Disables password-based authentication entirely
# Remediation: High severity - Prevents brute-force, password spraying, and credential stuffing
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 77-sshd-disable-password-auth
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
        - contents:
            # Plaintext content:
            # PasswordAuthentication no
            # PermitEmptyPasswords no
            source: data:,PasswordAuthentication%20no%0APermitEmptyPasswords%20no%0A
          mode: 0644
          overwrite: true
          path: /etc/ssh/sshd_config.d/02-disable-password-auth.conf

