---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: ztp-secret-provider
spec:
  conditions:
    - namespaceSelector:
        matchExpressions:
          - key: cluster.open-cluster-management.io/managedCluster
            operator: Exists
  provider:
    vault:
      server: {{ .spec.provider.vault.server | quote }}
      path: {{ .spec.provider.vault.path | quote }}
      version: {{ .spec.provider.vault.version | quote }}
      auth:
        tokenSecretRef:
          name: {{ .spec.provider.vault.auth.tokenSecretRef.name }}
          key: {{ .spec.provider.vault.auth.tokenSecretRef.key }}
          namespace: {{ .spec.provider.vault.auth.tokenSecretRef.namespace }}
