---
apiVersion: ols.openshift.io/v1alpha1
kind: OLSConfig
metadata:
  name: cluster
  namespace: openshift-lightspeed
spec:
  llm:
    providers:
      - name: openai
        type: openai
        credentialsSecretRef:
          name: llm-credentials
        models:
          - name: gpt-4o
        url: https://api.openai.com/v1
  ols:
    defaultModel: gpt-4o
    defaultProvider: openai
