apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: NMState.v1.nmstate.io
    operatorframework.io/bundle-unpack-min-retry-interval: 10m
    ran.openshift.io/ztp-deploy-wave: "2"
  name: openshift-nmstate
  namespace: openshift-nmstate
spec:
  targetNamespaces:
  - openshift-nmstate
  {{- if .spec.upgradeStrategy }}
  upgradeStrategy: Default
  {{- end }}
