apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- files:
    - extra-manifests/control-plane-load-kernel-modules.yaml
    - extra-manifests/worker-load-kernel-modules.yaml
    - extra-manifests/mc_rootless_pods_selinux.yaml
    - extra-manifests/sctp_module_mc.yaml
    - extra-manifests/kdump-master.yaml
    - extra-manifests/kdump-worker.yaml
    - extra-manifests/mount_namespace_config_master.yaml
    - extra-manifests/mount_namespace_config_worker.yaml
  name: extra-manifests-configmap
  namespace: cwl-site1
- files:
    - custom-manifests/mcp-worker-1.yaml
    - custom-manifests/mcp-worker-2.yaml
    - custom-manifests/mcp-worker-3.yaml
  name: custom-manifests-configmap
  namespace: cwl-site1

resources:
  - ns/cwl-site1.yaml
  - secrets/cwl-site1.yaml
  - cwl-site1.yaml

