---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - OtelNS.yaml
  - OtelOperGroup.yaml
  - OtelSubscription.yaml
  - OtelCollectorNS.yaml
  - kafka-secret.yaml
  - OtelRBAC-clusterRoleBinding.yaml
  - OtelRBAC-clusterRole.yaml
  - OtelCollector.yaml

