apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: $name
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: $mountpath
          role: $role
          serviceAccountRef:
            audiences:
            - https://kubernetes.default.svc
            name: external-secrets
            namespace: external-secrets
      caProvider:
        key: ca.crt
        name: vault-ca
        namespace: external-secrets
        type: ConfigMap
      path: $secretspath
      server: $url
      version: v2
