# optional
# count: 1
---
apiVersion: machineconfiguration.openshift.io/v1
kind: PinnedImageSet
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: worker-olm-pinned-images
spec:
{{ .spec | toYaml | indent 2 }}
