apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-45"
  labels:
    openshift.io/cluster-monitoring: "true"
    kubernetes.io/metadata.name: external-secrets-operator

