---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-server-certificate
  namespace: openshift-config
spec:
  commonName: "api.example.com"
  dnsNames:
  - api.example.com
  isCA: false
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: acme-issuer
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: api-server-cert
