---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: console-certificate
  namespace: openshift-console
spec:
  commonName: selfsigned-ca.dns.name
  isCA: false
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: acme-issuer
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: console-ca-root-secret
