# optional
# count: 1
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 40-load-kernel-modules-worker
spec:
  config:
  # Release info found in https://github.com/coreos/butane/releases
    ignition:
      version: 3.2.0
    storage:
      files:
      - contents:
          source: data:,
        mode: 420
        overwrite: true
        path: /etc/modprobe.d/kernel-blacklist.conf
      - contents:
          # Contents
          # ip_gre
          # nf_tables
          # nf_conntrack
          # nft_ct
          # nft_limit
          # nft_log
          # nft_nat
          # nft_chain_nat
          # nf_reject_ipv4
          # nf_reject_ipv6
          # nfnetlink_log
          {{- $userSource := "" }}
          {{- range $file := (or .spec.config.storage.files list) }}
            {{- if eq $file.path "/etc/modules-load.d/kernel-load.conf" }}
              {{- $userSource = $file.contents.source }}
            {{- end }}
          {{- end }}
          source: {{ template "validateBase64List" (list $userSource (list "ip_gre" "nf_tables" "nf_conntrack" "nft_ct" "nft_limit" "nft_log" "nft_nat" "nft_chain_nat" "nf_reject_ipv4" "nf_reject_ipv6" "nfnetlink_log" "mpls" "vrf")) }}
        mode: 420
        overwrite: true
        path: /etc/modules-load.d/kernel-load.conf
