---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: $name
  namespace: metallb-system
  annotations:
    ran.openshift.io/ztp-deploy-wave: "10"
spec:
  ipAddressPools:
  - $pool
  interfaces:
  - $int
