---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../reference-crs/optional/odf-internal/

patches:
  - target:
      group: ocs.openshift.io
      version: v1
      kind: StorageCluster
      name: ocs-storagecluster
    path: options-storage-cluster.yaml
