---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak-job-sa
  namespace: keycloak
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keycloak-secret-writer
  namespace: keycloak
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "list", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keycloak-job-secret-writer
  namespace: keycloak
subjects:
  - kind: ServiceAccount
    name: keycloak-job-sa
    namespace: keycloak
roleRef:
  kind: Role
  name: keycloak-secret-writer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-ingress-config
rules:
  - apiGroups: ["config.openshift.io"]
    resources: ["ingresses"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: allow-keycloak-job-to-read-ingress
subjects:
  - kind: ServiceAccount
    name: keycloak-job-sa
    namespace: keycloak
roleRef:
  kind: ClusterRole
  name: read-ingress-config
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-config-writer
  namespace: openshift-config
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["create", "get", "list", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-keycloak-job-in-openshift-config
  namespace: openshift-config
subjects:
  - kind: ServiceAccount
    name: keycloak-job-sa
    namespace: keycloak
roleRef:
  kind: Role
  name: secret-config-writer
  apiGroup: rbac.authorization.k8s.io
