apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  # if you change this name make sure the 'include' line in TunedPerformancePatch.yaml
  # matches this name: include=openshift-node-performance-${PerformanceProfile.metadata.name}
  # Also in file 'validatorCRs/informDuValidator.yaml':
  # name: 50-performance-${PerformanceProfile.metadata.name}
  name: openshift-node-performance-profile
  annotations:
    ran.openshift.io/ztp-deploy-wave: "10"
    ran.openshift.io/reference-configuration: "ran-du.redhat.com"
spec:
  additionalKernelArgs:
    - vfio_pci.enable_sriov=1
    - vfio_pci.disable_idle_d3=1
  cpu:
    isolated: $isolated
    reserved: $reserved
  # hardwareTuning allows maximum CPU frequencies to be set for reserved and isolated CPUs
  #hardwareTuning:
  #  isolatedCpuFreq: <max frequency in kHz>
  #  reservedCpuFreq: <max frequency in kHz>
  hugepages:
    defaultHugepagesSize: 1G
    pages:
      - size: 1G
        count: $count
        node: $node
  machineConfigPoolSelector:
    pools.operator.machineconfiguration.openshift.io/$mcp: ""
  nodeSelector:
    node-role.kubernetes.io/$mcp: ""
  numa:
    topologyPolicy: restricted
  realTimeKernel:
    # For x86_64, both realtime and non-realtime kernels are supported.
    # For aarch64, only the non-realtime kernel is supported with 64k pagesize.
    enabled: true
  workloadHints:
    # WorkloadHints defines the set of upper level flags for different type of workloads.
    # See https://github.com/openshift/cluster-node-tuning-operator/blob/master/docs/performanceprofile/performance_profile.md#workloadhints
    # for detailed descriptions of each item.
    # The configuration below is set for a low latency, performance mode.
    realTime: true
    highPowerConsumption: false
    perPodPowerManagement: false
