apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: myhub # need to match the same name put in install-config
rendezvousIP: 192.168.56.25 # one of the master IP 
hosts:

  - hostname: master-0
    role: master
    interfaces:
      - macAddress: 94:6d:ae:db:0b:64
        name: eno12399np0
      - macAddress: 94:6d:ae:db:0b:65
        name: eno12409np1
    networkConfig:
      interfaces:
      - name: infra-bond.46
        type: vlan
        state: up
        vlan:
          base-iface: infra-bond
          id: 46
        ipv4:
          enabled: true
          address: 
            - ip: 192.168.56.25 
              prefix-length: 25
          dhcp: false

      - name: infra-bond
        type: bond
        state: up
        ipv4:
          enabled: false
        ipv6: 
          enabled: false
        mac-address: 94:6d:ae:db:0b:64
        link-aggregation:
          mode: active-backup
          options:
            miimon: "100"
          port:
          - eno12399np0
          - eno12409np1
        mtu: 9126
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.56.1
            next-hop-interface: infra-bond.56
            table-id: 254
                
      dns-resolver:
        config:
          server:
            - 192.168.56.11     

  - hostname: master-1
    role: master
    interfaces:
      - macAddress: 94:6d:ae:da:dd:aa
        name: eno12399np0
      - macAddress: 94:6d:ae:da:dd:ab
        name: eno12409np1
    networkConfig:
      interfaces:
      - name: infra-bond.46
        type: vlan
        state: up
        vlan:
          base-iface: infra-bond
          id: 56
        
        ipv6:
          enabled: false
        ipv4:
          enabled: true
          address: 
            - ip: 192.168.56.26
              prefix-length: 25
          dhcp: false

        
      - name: infra-bond
        type: bond
        state: up
        ipv4:
          enabled: false
        ipv6:
          enabled: false
        mac-address: 94:6d:ae:da:dd:aa
        link-aggregation:
          mode: active-backup
          options:
            miimon: "100"
          port:
          - eno12399np0
          - eno12409np1
        mtu: 9126
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.56.1
            next-hop-interface: infra-bond.56
            table-id: 254
                
      dns-resolver:
        config:
          server:
            - 192.168.56.11
            

  - hostname: master-2
    role: master
    interfaces:
      - macAddress: 94:6d:ae:da:dc:d8
        name: eno12399np0
      - macAddress: 94:6d:ae:da:dc:d9
        name: eno12409np1
    networkConfig:
      interfaces:
      
      - name: infra-bond.56
        type: vlan
        state: up
        vlan:
          base-iface: infra-bond
          id: 56
        ipv4:
          enabled: true
          address: 
            - ip: 192.168.56.27
              prefix-length: 25
          dhcp: false

      - name: infra-bond
        type: bond
        state: up
        ipv4:
          enabled: false
        ipv6:
          enabled: false
        mac-address: 94:6d:ae:da:dc:d8
        link-aggregation:
          mode: active-backup
          options:
            miimon: "100"
          port:
          - eno12399np0
          - eno12409np1
        mtu: 9126
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.56.1
            next-hop-interface: infra-bond.56
            table-id: 254
                
      dns-resolver:
        config:
          server:
            - 192.168.56.11
