# optional
# count: 1
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: load-sctp-module
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
        - path: /etc/modprobe.d/sctp-blacklist.conf
<<<<<<< HEAD
<<<<<<< HEAD
          mode: 420
=======
          mode: 0644
>>>>>>> 1ac344c (Update load-sctp-module machineConfig to align with OCP-4.14)
=======
          mode: 420
>>>>>>> f4dc493 (umask converts 0644 to dec 420)
          overwrite: true
          contents:
            source: data:,
        - path: /etc/modules-load.d/sctp-load.conf
<<<<<<< HEAD
<<<<<<< HEAD
          mode: 420
=======
          mode: 0644
>>>>>>> 1ac344c (Update load-sctp-module machineConfig to align with OCP-4.14)
=======
          mode: 420
>>>>>>> f4dc493 (umask converts 0644 to dec 420)
          overwrite: true
          contents:
            source: data:,sctp
