# optional
# count: 1
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 40-load-kernel-modules-worker
spec:
  config:
    # Release info found in https://github.com/coreos/butane/releases
    ignition:
      version: 3.2.0
    storage:
      files:
      - contents:
          source: data:,
        mode: 420
        overwrite: true
        path: /etc/modprobe.d/kernel-blacklist.conf
      - contents:
          # Contents
          # nf_tables
          # nf_conntrack
          # nft_ct
          # nft_limit
          # nft_log
          # nft_nat
          # nft_chain_nat
          # nf_reject_ipv4
          # nf_reject_ipv6
          # nfnetlink_log
          source: data:text/plain;charset=utf-8;base64,bmZfdGFibGVzCm5mX2Nvbm50cmFjawpuZnRfY3QKbmZ0X2xpbWl0Cm5mdF9sb2cKbmZ0X25hdApuZnRfY2hhaW5fbmF0Cm5mX3JlamVjdF9pcHY0Cm5mX3JlamVjdF9pcHY2Cm5mbmV0bGlua19sb2cKCg==
        mode: 420
        overwrite: true
        path: /etc/modules-load.d/kernel-load.conf
