---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
    operatorframework.io/bundle-unpack-min-retry-interval: 10m
  name: cluster-logging
  namespace: openshift-logging
spec:
  targetNamespaces:
  - openshift-logging
  {{- if .spec.upgradeStrategy }}
  upgradeStrategy: Default
  {{- end }}
