---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  name: {{ .metadata.name }}
  namespace: openshift-logging
spec:
  targetNamespaces:
  - openshift-logging
  {{- if .spec.upgradeStrategy }}
  upgradeStrategy: Default
  {{- end }}
