apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: lvms-operator-operatorgroup
  namespace: openshift-storage
  annotations:
    operatorframework.io/bundle-unpack-min-retry-interval: 10m
    ran.openshift.io/ztp-deploy-wave: "2"
spec:
  targetNamespaces:
  - openshift-storage
  {{- if .spec.upgradeStrategy }}
  upgradeStrategy: Default
  {{- end }}
