---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: core-customer-policies-22
policyDefaults:
  namespace: ztp-core-policies
  policySets: []
  placement:
    labelSelector:
      matchLabels:
        common: "core"
        version: "4.22"
  remediationAction: "inform"
policies:
  # unpause baseline configuration
  - name: custom-mcp-unpause-22
    policyAnnotations:
      ran.openshift.io/ztp-deploy-wave: "200"
    placement:
      labelSelector:
        matchExpressions:
          - key: common
            operator: In
            values:
              - "core"
          - key: version
            operator: In
            values:
              - "4.22"
          - key: ztp-done
            operator: DoesNotExist
    # The policy unpauses MCPs that were paused during initial creation
    # and sets 'maxUnavailable' parameter to 100% to speed up the deployment.
    # This is only required once as part of the deployment optimization
    # therefore it's not required to re-evaluate it after initial deployment.
    evaluationInterval:
      compliant: never
    manifests:
      # The MCPs should be added as extra manifests at installation time. Their
      # inclusion here will reset the pause to false, allowing the MCPs to update
      - path: reference-crs/custom-manifests/mcp-worker-1.yaml
        patches:
        - spec:
            paused: false
            maxUnavailable: 100%
          status:
            conditions:
            - type: Updated
              status: "True"
            - type: Updating
              status: "False"

      - path: reference-crs/custom-manifests/mcp-worker-2.yaml
        patches:
        - spec:
            paused: false
            maxUnavailable: 100%
          status:
            conditions:
            - type: Updated
              status: "True"
            - type: Updating
              status: "False"

      - path: reference-crs/custom-manifests/mcp-worker-3.yaml
        patches:
        - spec:
            paused: false
            maxUnavailable: 100%
          status:
            conditions:
            - type: Updated
              status: "True"
            - type: Updating
              status: "False"

  - name: core-custom-mcp-set-maxavailable-22
    policyAnnotations:
      ran.openshift.io/ztp-deploy-wave: "201"
    manifests:
      # This sets the desired maxUnavailable on the customMCPs
      - path: reference-crs/custom-manifests/mcp-worker-1.yaml
        patches:
        - spec:
            maxUnavailable: 1
      - path: reference-crs/custom-manifests/mcp-worker-2.yaml
        patches:
        - spec:
            maxUnavailable: 1
      - path: reference-crs/custom-manifests/mcp-worker-3.yaml
        patches:
        - spec:
            maxUnavailable: 1
