---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: core-customer-policies
policyDefaults:
  namespace: ztp-core-policies
  policySets: []
  placement:
    clusterSelectors:
      common: "core"
      version: "4.20"
  remediationAction: "inform"
policies:
  # unpause baseline configuration
  - name: custom-mcp-unpause
    policyAnnotations:
      ran.openshift.io/ztp-deploy-wave: "200"
    manifests:
      # The MCPs should be added as extra manifests at installation time. Their
      # inclusion here will reset the pause to false, allowing the MCPs to update
      - path: reference-crs/custom-manifests/mcp-worker-1.yaml
        patches:
        - spec:
            paused: false
            maxUnavailable: 100%
          status:
            conditions:
            - type: Updated
              status: "True"
            - type: Updating
              status: "False"

      - path: reference-crs/custom-manifests/mcp-worker-2.yaml
        patches:
        - spec:
            paused: false
            maxUnavailable: 100%
          status:
            conditions:
            - type: Updated
              status: "True"
            - type: Updating
              status: "False"

      - path: reference-crs/custom-manifests/mcp-worker-3.yaml
        patches:
        - spec:
            paused: false
            maxUnavailable: 100%
          status:
            conditions:
            - type: Updated
              status: "True"
            - type: Updating
              status: "False"

  - name: core-custom-mcp-set-maxavailable
    policyAnnotations:
      ran.openshift.io/ztp-deploy-wave: "201"
    manifests:
      # This sets the desired maxUnavailable on the customMCPs
      - path: reference-crs/custom-manifests/mcp-worker-1.yaml
        patches:
        - spec:
            maxUnavailable: 1
      - path: reference-crs/custom-manifests/mcp-worker-2.yaml
        patches:
        - spec:
            maxUnavailable: 1
      - path: reference-crs/custom-manifests/mcp-worker-3.yaml
        patches:
        - spec:
            maxUnavailable: 1
