---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: openshift-local-storage
  name: openshift-local-storage
  annotations:
    ran.openshift.io/ztp-deploy-wave: "5"
