# required: yes
# count: 1
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: sriov-network-operators
  namespace: openshift-sriov-network-operator
  annotations:
    operatorframework.io/bundle-unpack-min-retry-interval: 10m
spec:
  targetNamespaces:
  - openshift-sriov-network-operator
