---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: mgh
  namespace: multicluster-global-hub
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
spec:
  channel: release-1.7
  installPlanApproval: Automatic
  name: multicluster-global-hub-operator-rh
  source: redhat-operators-disconnected
  sourceNamespace: openshift-marketplace
