---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kafka-secret
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "15"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: local-kafka-store
  target:
    name: kafka-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ca-bundle.crt: "{{ .ca_bundle }}"
        tls.crt: "{{ .tls_crt }}"
        tls.key: "{{ .tls_key }}"
  data: # data for the template above
  - secretKey: ca_bundle
    remoteRef:
      key: mgmt-kafka-cluster-ca-cert
      property: ca.crt
  - secretKey: tls_crt
    remoteRef:
      key: mgmt-kafka-clients-ca-cert
      property: ca.crt
  - secretKey: tls_key
    remoteRef:
      key: mgmt-kafka-clients-ca
      property: ca.key

