apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: sriov-network-operators
  namespace: openshift-sriov-network-operator
  annotations:
    operatorframework.io/bundle-unpack-min-retry-interval: 10m
    ran.openshift.io/ztp-deploy-wave: "2"
spec:
  targetNamespaces:
  - openshift-sriov-network-operator
  {{- if .spec.upgradeStrategy }}
  upgradeStrategy: Default
  {{- end }}
