---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme-issuer
spec:
  # Example based on: https://cert-manager.io/docs/configuration/acme/#creating-a-basic-acme-issuer
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: your-email@example.com
    privateKeySecretRef:
      name: acme-account-key
    solvers:
    - dns01:
        route53:
          region: us-east-1
          # Replace with your DNS provider configuration
          # See: https://cert-manager.io/docs/configuration/acme/dns01/
