---
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  platform:
    channels:
    - name: stable-5.0
      type: ocp
      # Adjust minVersion and maxVersion according to your required releases. This allows you to
      # minimize the mirrored content to only what is needed for your deployment. Note that only
      # versions which are mirrored to the disconnected registry can be installed, so only versions
      # listed here should be referenced in installation CRs (eg ClusterImageSet / imageSetRef).
      minVersion: 5.0.0
      maxVersion: 5.0.2
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v5.0
    targetCatalog: openshift-marketplace/redhat-operators-disconnected
    packages:
    - name: advanced-cluster-management
      defaultChannel: release-5.0
      channels:
      - name: release-5.0
    - name: multicluster-engine
      defaultChannel: stable-5.0
      channels:
      - name: stable-5.0
    - name: openshift-gitops-operator
      defaultChannel: gitops-1.21
      channels:
      - name: gitops-1.21
    - name: redhat-oadp-operator
      channels:
      - name: stable
    - name: topology-aware-lifecycle-manager
      channels:
      - name: stable
    - name: local-storage-operator
      channels:
      - name: stable
    - name: cluster-logging
      defaultChannel: stable-6.6
      channels:
      - name: stable-6.6
    - name: odf-operator
      defaultChannel: stable-5.0
      channels:
      - name: stable-5.0
    - name: odf-external-snapshotter-operator
      defaultChannel: stable-5.0
      channels:
      - name: stable-5.0
    - name: odf-dependencies
      defaultChannel: stable-5.0
      channels:
      - name: stable-5.0
    - name: odf-csi-addons-operator
      defaultChannel: stable-5.0
      channels:
      - name: stable-5.0
    - name: ocs-client-operator
      defaultChannel: stable-5.0
      channels:
      - name: stable-5.0
    - name: cephcsi-operator
      defaultChannel: stable-5.0
      channels:
      - name: stable-5.0
    - name: odf-prometheus-operator
      defaultChannel: stable-5.0
      channels:
      - name: stable-5.0
    - name: odf-multicluster-orchestrator
      defaultChannel: stable-5.0
      channels:
      - name: stable-5.0
    - name: ocs-operator
      defaultChannel: stable-5.0
      channels:
      - name: stable-5.0
    - name: rook-ceph-operator
      defaultChannel: stable-5.0
      channels:
      - name: stable-5.0
    - name: mcg-operator
      defaultChannel: stable-5.0
      channels:
      - name: stable-5.0
    - name: odr-hub-operator
      defaultChannel: stable-5.0
      channels:
      - name: stable-5.0
    - name: odr-cluster-operator
      defaultChannel: stable-5.0
      channels:
      - name: stable-5.0
    - name: recipe
      defaultChannel: stable-5.0
      channels:
      - name: stable-5.0
    - name: openshift-cert-manager-operator
      defaultChannel: stable-v1
      channels:
      - name: stable-v1
  additionalImages:
  - name: registry.redhat.io/ubi8/ubi:latest
  - name: registry.redhat.io/openshift4/ztp-site-generate-rhel8:v5.0
  - name: registry.redhat.io/rhel8/support-tools:latest
  - name: registry.redhat.io/rhacm2/multicluster-operators-subscription-rhel9:v5.0
  helm: {}
