---
apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
  annotations:
    ran.openshift.io/ztp-deploy-wave: "100"
spec:
  servingCerts:
    namedCertificates: {{ if .spec.servingCerts.namedCertificates }}
{{ .spec.servingCerts.namedCertificates | toYaml | nindent 4 }}{{ else }}[]{{ end }}
