# required
# Disables iptables-alerter to prevent high CPU usage in production (OCPBUGS-87026, OCPBUGS-73767)
# Partners must test iptables usage in pre-production and migrate to nftables before RHEL10
# KCS: https://access.redhat.com/solutions/7134521
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: iptables-alerter-config
  namespace: openshift-network-operator
data:
  enabled: "false"
