apiVersion: v1
kind: Secret
metadata:
  name: osp-secret
  namespace: osp18
  annotations:
    ran.openshift.io/ztp-deploy-wave: "2"
type: Opaque
data:
  AdminPassword: dmZ2cmN4cHE3bXp2dmJ0Z2RobjU4cHRobg==
  AodhPassword: ZjU5bG44ZHhucXY4NXQyODYyN2s5N3J3bQ==
  BarbicanPassword: OXJzMjc3ZjJsYnQ0enRtdmg5ZGt4cjJyOA==
  CeilometerPassword: d3M5dGdjMmx6em0yOWxobWhsZDd0czk2cg==
  CinderPassword: OTZoemN6aHJrZDc3aHdkdDc1N3hqaG52Yg==
  DesignatePassword: bng4azhucnBuaDJ4YjhyaDJrdGY1cWR2Nw==
  GlancePassword: bWN0MmdweGZzbmNxdjRjeGNjcGZ4NnZrZA==
  HeatAuthEncryptionKey: dHpwc2JtdmNuZ2NrYzlnNmg4YnpmYnI4NWRtemYybm4=
  HeatPassword: cnhybDdxNmY5c3RraHJ4YzV2OGpmcDg2NA==
  HeatStackDomainAdminPassword: dmtxYnNudjlyaHE4eGd2amhkcW5qazY3NA==
  IronicPassword: emhrbWo1NTk0Ymg2YndxOGc3OXc1dGpmcQ==
  ManilaPassword: Y2h0NndrY2oyNXd4enZraGptZjY5ajZxag==
  NeutronPassword: MjdiNmpucDh0NDVsczI4MnhjeDc1N2Q1NQ==
  NovaPassword: NGo0eHRsdmhxcGRiZnJzaHY3OWs3OHN4dA==
  OctaviaPassword: cW42bGtkbDdwN3R2YjcyeHI1aGhncHg3dw==
  PlacementPassword: dm03cHdqNGhwbHY0cm52Ym50c2N6Ym50cQ==
  SwiftPassword: cmI1aGRjc201eHM5ZGdwamd3Y3M1eDVzbg==
  CinderDatabasePassword: b3BlbnN0YWNr
  DatabasePassword: b3BlbnN0YWNr
  DbRootPassword: b3BlbnN0YWNr
  DesignateDatabasePassword: b3BlbnN0YWNr
  GlanceDatabasePassword: b3BlbnN0YWNr
  HeatDatabasePassword: b3BlbnN0YWNr
  IronicDatabasePassword: b3BlbnN0YWNr
  IronicInspectorDatabasePassword: b3BlbnN0YWNr
  IronicInspectorPassword: b3BlbnN0YWNr
  KeystoneDatabasePassword: b3BlbnN0YWNr
  ManilaDatabasePassword: b3BlbnN0YWNr
  MetadataSecret: b3BlbnN0YWNr
  NeutronDatabasePassword: b3BlbnN0YWNr
  NovaAPIDatabasePassword: b3BlbnN0YWNr
  NovaAPIMessageBusPassword: b3BlbnN0YWNr
  NovaCell0DatabasePassword: b3BlbnN0YWNr
  NovaCell0MessageBusPassword: b3BlbnN0YWNr
  NovaCell1DatabasePassword: b3BlbnN0YWNr
  NovaCell1MessageBusPassword: b3BlbnN0YWNr
  OctaviaDatabasePassword: b3BlbnN0YWNr
  PlacementDatabasePassword: b3BlbnN0YWNr
