---
apiVersion: v1
kind: Secret
metadata:
  name: ztp-repo-workload
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@gitlab.example.com:namespace/repo.git
  insecure: "false"
  username: username
  password: password
  forceHttpBasicAuth: "true"

