---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  name: cert-manager-operator
  namespace: openshift-console
spec:
  upgradeStrategy: Default
