---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: local-kafka-store
  annotations:
    argocd.argoproj.io/sync-wave: "-25"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    kubernetes:
      # Points back to the local cluster API
      remoteNamespace: kafka-cluster
      server:
        url: https://kubernetes.default.svc
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: external-secrets
      auth:
        serviceAccount:
          name: external-secrets # A service account with access to kafka-cluster namespace
          namespace: external-secrets

