---
apiVersion: v1
kind: Secret
metadata:
  name: vault-reviewer-token
  namespace: vault
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
    kubernetes.io/service-account.name: vault-reviewer
type: kubernetes.io/service-account-token
