apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
  annotations:
    ran.openshift.io/ztp-deploy-wave: "10"
type: Opaque
stringData:
  thanos.yaml: $update

