---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../other-crs/optional/monitoring-kafka/

patches:
  - target:
      group: opentelemetry.io
      version: v1beta1
      kind: OpenTelemetryCollector
      name: otel-metrics-gateway
    path: OtelCollector-patch.yaml
