apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
  annotations:
    ran.openshift.io/ztp-deploy-wave: "1"
data:
  config.yaml: |
    alertmanagerMain:
      enabled: false
    telemeterClient:
      enabled: false
    prometheusK8s:
      additionalAlertmanagerConfigs:
      - apiVersion: v2
        bearerToken:
          key: token
          name: observability-alertmanager-accessor
        scheme: https
        staticConfigs:
        #do we need to create a policy to copy acm-route in the configMap?
        - {{hub fromConfigMap "" "acm-route" "route" hub}}
        tlsConfig:
          ca:
            key: service-ca.crt
            name: hub-alertmanager-router-ca
          insecureSkipVerify: false
      externalLabels:
        #from where will we get clusterID
        managed_cluster: {{hub index .ManagedClusterLabels "clusterID" hub}}
       retention: 24h
