# required
# count: 1
apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  {{- $isControlPlane := false }}
  {{- if hasKey .spec "machineConfigPoolSelector" }}
    {{- if hasKey .spec.machineConfigPoolSelector "pools.operator.machineconfiguration.openshift.io/master" }}
      {{- $isControlPlane = true }}
    {{- end }}
  {{- end }}
  name: {{ if $isControlPlane }}control-plane-profile{{ else }}{{ .metadata.name }}{{ end }}
  annotations:
    {{- if $isControlPlane }}
    # systemReserved: when used, it should be tailored for each environment.
    {{- $rawConfig := index (.metadata.annotations | default dict) "kubeletconfig.experimental" }}
    {{- $config := $rawConfig | default "{}" | fromJson }}
    {{- if hasKey $config "allowedUnsafeSysctls" }}
      {{- if ne (len $config.allowedUnsafeSysctls) 0 }}
        {{- fail "Control plane PerformanceProfile must not have any allowedUnsafeSysctls" }}
      {{- end }}
    {{- end }}
    kubeletconfig.experimental: |
      {
       "systemReserved":{{ $config.systemReserved | toJson }}
      }
    {{- else }}
    # Some pods want the kernel stack to ignore IPv6 router Advertisement.
      {{ $allowedSysctls := (list
          "net.ipv6.conf.default.accept_ra"
          "net.ipv6.conf.all.disable_ipv6"
          "net.ipv6.conf.default.disable_ipv6"
          "net.ipv4.conf.all.disable_policy"
          "net.ipv4.conf.default.disable_policy"
          "net.ipv6.conf.all.disable_policy"
          "net.ipv6.conf.default.disable_policy"
          "net.ipv4.conf.all.rp_filter"
          "net.ipv4.conf.default.rp_filter"
          "net.ipv6.conf.all.hop_limit"
          "net.ipv6.conf.default.hop_limit"
        ) }}
      {{- template "kubeletconfigExperimental" (list (index (.metadata.annotations | default dict) "kubeletconfig.experimental") (list "net.ipv6.conf.all.accept_ra")  $allowedSysctls) }}
    {{- end }}
spec:
  additionalKernelArgs:
    {{- template "unorderedList" (list .spec.additionalKernelArgs (list
      "module_blacklist=irdma"
      ) (list
      "intel_idle.max_cstate=0"
      ) ) }}
  cpu:
    isolated: {{ .spec.cpu.isolated }}
    reserved: {{ .spec.cpu.reserved }}
  globallyDisableIrqLoadBalancing: false
  {{- if hasKey .spec "hugepages" }}
  hugepages:
    defaultHugepagesSize: 1G
    pages:
        {{- range .spec.hugepages.pages }}
        - size: {{ .size  }}
          count: {{ .count }}
          {{if ne (index . "node") nil }}
          node: {{ .node }}
          {{- end }}
        {{- end }}
  {{- end }}
  {{- if hasKey .spec "kernelPageSize" }}
  kernelPageSize: {{ .spec.kernelPageSize }}
  {{- end }}
  {{- if hasKey .spec "machineConfigPoolSelector" }}
  machineConfigPoolSelector:
    {{- .spec.machineConfigPoolSelector | toYaml | nindent 4 }}
  {{- end }}
  {{- if hasKey .spec "nodeSelector" }}
  nodeSelector:
    {{- .spec.nodeSelector | toYaml | nindent 4 }}
  {{- end }}
  workloadHints:
    realTime: false
    highPowerConsumption: false
    perPodPowerManagement: true
  realTimeKernel:
    enabled: false
  numa:
    # All guaranteed QoS containers get resources from a single NUMA node
    topologyPolicy: "single-numa-node"
  {{- if hasKey .spec.net "userLevelNetworking" }}
  net:
    userLevelNetworking: {{ if $isControlPlane }}true{{ else }}false{{ end }}
  {{- end }}
