# required
# count: 1
apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  name: {{ .metadata.name }}
  annotations:
    # Some pods want the kernel stack to ignore IPv6 router Advertisement.
    {{- if .metadata }}
      {{ $allowedSysctls := (list
          "net.ipv6.conf.default.accept_ra"
          "net.ipv6.conf.all.disable_ipv6"
          "net.ipv6.conf.default.disable_ipv6"
          "net.ipv4.conf.all.disable_policy"
          "net.ipv4.conf.default.disable_policy"
          "net.ipv6.conf.all.disable_policy"
          "net.ipv6.conf.default.disable_policy"
          "net.ipv4.conf.all.rp_filter"
          "net.ipv4.conf.default.rp_filter"
          "net.ipv6.conf.all.hop_limit"
          "net.ipv6.conf.default.hop_limit"
        ) }}
      {{- template "kubeletconfigExperimental" (list (index (.metadata.annotations | default dict) "kubeletconfig.experimental") (list "net.ipv6.conf.all.accept_ra")  $allowedSysctls) }}
    {{- end }}
spec:
  additionalKernelArgs:
    {{- template "unorderedList" (list .spec.additionalKernelArgs (list
      "module_blacklist=irdma"
      ) (list
      "intel_idle.max_cstate=0"
      ) ) }}
  cpu:
    # node0 CPUs: 0-17,36-53
    # node1 CPUs: 18-34,54-71
    # siblings: (0,36), (1,37)...
    # we want to reserve the first Core of each NUMA socket
    #
    # no CPU left behind! all-cpus == isolated + reserved
    isolated: {{ .spec.cpu.isolated }} # eg 1-17,19-35,37-53,55-71
    reserved: {{ .spec.cpu.reserved }} # eg 0,18,36,54
  # Guaranteed QoS pods will disable IRQ balancing for cores allocated to the pod.
  # default value of globallyDisableIrqLoadBalancing is false
  globallyDisableIrqLoadBalancing: false
  hugepages:
    defaultHugepagesSize: 1G
    pages:
        {{- range .spec.hugepages.pages }}
        - size: {{ .size  }}
          count: {{ .count }}
          {{if ne (index . "node") nil }}
          node: {{ .node }}
          {{- end }}
        {{- end }}
  {{- if hasKey .spec "machineConfigPoolSelector" }}
  machineConfigPoolSelector:
    {{- .spec.machineConfigPoolSelector | toYaml | nindent 4 }}
#    # For SNO: machineconfiguration.openshift.io/role: 'master'
#    pools.operator.machineconfiguration.openshift.io/worker: ''
  {{- end }}
  {{- if hasKey .spec "nodeSelector" }}
  nodeSelector:
    {{- .spec.nodeSelector | toYaml | nindent 4 }}
#    # For SNO: node-role.kubernetes.io/master: ""
#    node-role.kubernetes.io/worker: ""
  {{- end }}
  workloadHints:
    realTime: false
    highPowerConsumption: false
    perPodPowerManagement: true
  realTimeKernel:
    enabled: false
  numa:
    # All guaranteed QoS containers get resources from a single NUMA node
    topologyPolicy: "single-numa-node"
  {{- if hasKey .spec.net "userLevelNetworking" }}
  net:
    userLevelNetworking: false
  {{- end }}
