apiVersion: tuned.openshift.io/v1
kind: Tuned
metadata:
  name: {{ .metadata.name }}
  namespace: openshift-cluster-node-tuning-operator
  annotations:
    ran.openshift.io/ztp-deploy-wave: "10"
spec:
  profile:
    - name: {{ .metadata.name }}
      # Please note:
      # - The 'include' line must match the associated PerformanceProfile name, following below pattern
      #   include=openshift-node-performance-${PerformanceProfile.metadata.name}
      data: |
        [main]
        summary=Top-level core performance tuning overrides
        include=openshift-node-performance-openshift-node-performance-profile
        [sysctl]
        kernel.panic_on_unrecovered_nmi=1
  recommend:
  {{- range .spec.recommend }}
    - machineConfigLabels:
        {{- .machineConfigLabels | toYaml | nindent 8 }}
      priority: {{ .priority | default 18 }}
      profile: {{ $.metadata.name }}
  {{- end }}
