apiVersion: tuned.openshift.io/v1
kind: Tuned
metadata:
  name: {{ .metadata.name }}
  namespace: openshift-cluster-node-tuning-operator
  annotations:
    ran.openshift.io/ztp-deploy-wave: "10"
spec:
  profile:
{{- range .spec.profile }}
    - name: {{ .name }}
      # Please note:
      # - The 'include' line must match the associated PerformanceProfile name, following below pattern
      #   include=openshift-node-performance-${PerformanceProfile.metadata.name}
      data: |
{{- .data | nindent 8 }}
{{- end }}
  recommend:
{{- range .spec.recommend }}
    - machineConfigLabels:
{{- .machineConfigLabels | toYaml | nindent 8 }}
      priority: {{ .priority | default 18 }}
      profile: {{ .profile }}
{{- end }}
