apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: cluster-logging
  namespace: openshift-logging
  annotations:
    operatorframework.io/bundle-unpack-min-retry-interval: 10m
spec:
  targetNamespaces:
  - openshift-logging
  {{- if .spec.upgradeStrategy }}
  upgradeStrategy: Default
  {{- end }}
