apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  {{- if .spec.outputs }}
  outputs:
    {{- .spec.outputs | toYaml | nindent 2 }}
  {{- end }}
  {{- if .spec.filters }}
  filters:
    {{- .spec.filters | toYaml | nindent 2 }}
  {{- end }}
  {{- if .spec.pipelines }}
  pipelines:
    {{- .spec.pipelines | toYaml | nindent 2 }}
  {{- end }}
  serviceAccount:
    name: {{ .spec.serviceAccount.name }}
  {{- if .spec.managementState }}
  managementState: {{ .spec.managementState }}
  {{- end }}
