apiVersion: v1
kind: Namespace
metadata:
  name: openshift-logging
  annotations:
    workload.openshift.io/allowed: management
  {{- if .metadata.labels }}
  labels:
    {{- template "allowLabels" (list .metadata.labels
        "pod-security.kubernetes.io"
    ) }}
  {{- end }}
