apiVersion: v1
kind: Secret
metadata:
  name: logging-loki-s3
  namespace: openshift-logging
stringData:
  access_key_id: {{ .stringData.access_key_id }}
  access_key_secret: {{ .stringData.access_key_secret }}
  bucketnames: {{ .stringData.bucketnames }}
  endpoint: {{ .stringData.endpoint }}
  region: {{ .stringData.region }}
