apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hub-rds-cluster-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-ocm-cluster-manager-admin: "true"
rules:
- apiGroups:
  - siteconfig.open-cluster-management.io
  resources:
  - clusterinstances
  verbs:
  - create
  - patch
