---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: obs-route-policy-placement
  namespace: open-cluster-management-observability
  annotations:
    argocd.argoproj.io/sync-wave: "-25"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: local-cluster
              operator: In
              values:
                - "true"
  tolerations:
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
