apiVersion: v1
data:
  password: dGVzdHBhc3N3b3Jk
  username: dGVzdHVzZXI=
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "-20"    
type: Opaque
