apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- example-sno.yaml
- example-3node.yaml
- example-standard.yaml
# - namespace.yaml
# - secret.yaml

## Reference install manifests: telco-ran/install/extra-manifests/
## Optional manifests (enable-crun): telco-ran/install/custom-manifests/
## See telco-ran/install/kustomization.yaml for a configMapGenerator example.
#
# configMapGenerator:
# - files:
#   - ../../install/extra-manifests/01-container-mount-ns-and-kubelet-conf-master.yaml
#   ...
#   name: ran-extra-manifests-configmap
#   namespace: <namespace>
# generatorOptions:
#   disableNameSuffixHash: true
