#
# Get the following files from the Ceph cluster:
#   /etc/ceph/ceph.client.openstack.keyring
#   /etc/ceph/ceph.conf
#
# Use the base64 of these files to create the secret below
#   cat ceph.client.openstack.keyring | base64 -w 0
#   cat ceph.conf | base64 -w 0
#
apiVersion: v1
data:
  ceph.client.openstack.keyring: '{{fromSecret "openstack" "rhoso-ceph" "ceph-keyring"}}'
  ceph.conf: '{{fromSecret "openstack" "rhoso-ceph" "ceph-conf"}}'
kind: Secret
metadata:
  name: ceph-conf-files
  namespace: openstack
type: Opaque

