---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generators:
- aiwl-baseline.yaml
- aiwl-odf-external.yaml
- aiwl-odf-internal.yaml
- aiwl-kafka.yaml
- aiwl-rhoai.yaml
- aiwl-auth-idm.yaml
- aiwl-finish.yaml
resources:
- clusterimageset42016.yaml
- resources
- template-values/regional.yaml
- template-values/hw-types.yaml
- template-values/cwl-site4.yaml
