---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/amq-streams.kafka-cluster: ""
  name: amq-streams
  namespace: kafka-cluster
spec:
  channel: stable
  name: amq-streams
  source: redhat-operators-disconnected
  sourceNamespace: openshift-marketplace
  installPlanApproval: Manual
status:
  state: AtLatestKnown

