---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend-mgmt1
  namespace: mgmt1
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes-mgmt1
          role: mgmt1
          serviceAccountRef:
            audiences:
            - https://kubernetes.default.svc
            name: default
      caProvider:
        key: ca.crt
        name: vault-ca
        namespace: external-secrets
        type: ConfigMap
      path: ztp/mgmt1
      server: https://vault-server.apps.ghub.example.com
      version: v2
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bmh-secret-v1
  namespace: mgmt1
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: ztp/mgmt1/bmc-v1
      metadataPolicy: None
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: SecretStore
    name: vault-backend-mgmt1
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: bmh-secret-v1
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: assisted-deployment-pull-secret
  namespace: mgmt1
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: ztp/mgmt1/pullsecret
      metadataPolicy: None
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: SecretStore
    name: vault-backend-mgmt1
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: assisted-deployment-pull-secret
