apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneDeployment
metadata:
  name: data-plane-deploy-dpdk
  namespace: openstack
  annotations:
    ran.openshift.io/ztp-deploy-wave: "10"
spec:
  nodeSets:
    - nodeset-dpdk

