---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generators:
- core-baseline.yaml
- core-overlay.yaml
- cwl-additions.yaml
- cwl-odf-external.yaml
- cwl-odf-internal.yaml
- cwl-kafka.yaml
- cwl-lab-only.yaml
- cwl-auth-idm.yaml
- core-finish.yaml
resources:
- clusterimageset42016.yaml
- resources
- template-values/regional.yaml
- template-values/hw-types.yaml
- template-values/cwl-site1.yaml
