apiVersion: v1
kind: Secret
metadata:
  name: tempo-bucket-secret
  namespace: openshift-tempo-operator
  annotations:
    ran.openshift.io/ztp-deploy-wave: "10"
type: Opaque
data:
  access_key_id: 
  access_key_secret:
  bucket:
  endpoint:
