apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack 
metadata:
  name: simplest
  namespace: openshift-tempo-operator
spec:
  storage: 
    secret: 
      name: tempo-bucket-secret
      type: s3
    tls:
      #caName: tempo-s3-ca
      caName: openshift-service-ca.crt
      enabled: true
  storageSize: 10Gi 
  resources:
    total:
      limits:
        memory: 2Gi
        cpu: 2000m
  tenants:
    mode: openshift 
    authentication: 
      - tenantName: dev 
        tenantId: "1610b0c3-c509-4592-a256-a1871353dbfa" 
      - tenantName: prod
        tenantId: "1610b0c3-c509-4592-a256-a1871353dbfb"
  template:
    gateway:
      enabled: true 
    queryFrontend:
      jaegerQuery:
        enabled: true 
