---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend-cwl-site3
  namespace: cwl-site3
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes-mgmt1
          role: mgmt1
          serviceAccountRef:
            audiences:
            - https://kubernetes.default.svc
            name: default
      caProvider:
        key: ca.crt
        name: vault-ca
        namespace: external-secrets
        type: ConfigMap
      path: ztp/cwl-site3
      server: https://vault-server.apps.ghub.npss.bos2.lab
      version: v2
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bmh-secret-dell
  namespace: cwl-site3
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: ztp/cwl-site3/bmc-dell
      metadataPolicy: None
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: SecretStore
    name: vault-backend-cwl-site3
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: bmh-secret-dell
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: assisted-deployment-pull-secret
  namespace: cwl-site3
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: ztp/cwl-site3/pullsecret
      metadataPolicy: None
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: SecretStore
    name: vault-backend-cwl-site3
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: assisted-deployment-pull-secret
