---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  namespace: openshift-gitops
spec:
  destinations:
    # Hub policies are copied by ACM to the local-cluster namespace. This causes
    # ArgoCD/GitOps to see those policies and flag them for pruning due to argocd
    # annotations which remain on the copies. Prevent this confusion by restricting
    # GitOps from managing resources in the local-cluster namespace where the
    # copies are being created.
    - namespace: '!local-cluster'
      server: '*'
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
    - group: ""
      kind: Namespace
