---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kafkaNS.yaml
  - kafkaOperatorGroup.yaml
  - kafkaSubscription.yaml
  - kafkaTopic.yaml
  - kafkaNodePool.yaml 
  - kafka.yaml

