apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- example-sno.yaml
- example-3node.yaml
- example-standard.yaml
# - namespace.yaml
# - secret.yaml

# Build the ConfigMap containing all install-time MachineConfigs.
# The ClusterInstance examples reference this ConfigMap via extraManifestsRefs.
# Adjust the file list to match the desired set of manifests for the target cluster type.
configMapGenerator:
- name: sno-extra-manifest-configmap
  files:
  - ../extra-manifests/01-container-mount-ns-and-kubelet-conf-master.yaml
  - ../extra-manifests/01-disk-encryption-pcr-rebind-master.yaml
  - ../extra-manifests/03-sctp-machine-config-master.yaml
  - ../extra-manifests/06-kdump-master.yaml
  - ../extra-manifests/07-sriov-related-kernel-args-master.yaml
  - ../extra-manifests/08-set-rcu-normal-master.yaml
  - ../extra-manifests/09-openshift-marketplace-ns.yaml
  - ../extra-manifests/10-rename-gnrd-interfaces-master.yaml
  - ../extra-manifests/99-sync-time-once-master.yaml
generatorOptions:
  disableNameSuffixHash: true
