---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cwl-site2
  namespace: ztp-core-policies
data:
  kafka-broker: "mgmt-kafka-kafka-bootstrap-kafka-cluster.apps.mgmt1.npss.bos2.lab:443"
  vault-server: "https://vault-server.apps.ghub.npss.bos2.lab"
  ldap-server: "idm1mgmt1.npss.bos2.lab"
  quay-fqdn: "registry.bastion.npss.bos2.lab:9500"
  # RHOSO variables
  dns-domain: osp.cwl-site2.npss.bos2.lab
  dns-server: 192.168.22.4
  ntp-server: 192.168.22.2
  satellite-fqdn: satellite.mgmt1.npss.bos2.lab
  ctlplane-interface: "bond0"
  ctlplane-cidr: "10.62.62.0/24"
  ctlplane-gw: "10.62.62.1"
  ctlplane-cp-range-start: "10.62.62.30"
  ctlplane-cp-range-end: "10.62.62.70"
  ctlplane-dp-range-start: "10.62.62.100"
  ctlplane-dp-range-end: "10.62.62.250"
  ctlplane-metallb-addrpool: 10.62.62.80-10.62.62.90
  internalapi-interface: "bond1.93"
  internalapi-cidr: "10.2.120.0/24"
  internalapi-vlan: "93"
  internalapi-cp-range-start: "10.2.120.30"
  internalapi-cp-range-end: "10.2.120.70"
  internalapi-dp-range-start: "10.2.120.100"
  internalapi-dp-range-end: "10.2.120.250"
  internalapi-metallb-addrpool: 10.2.120.80-10.2.120.90
  storage-interface: "bond1.94"
  storage-cidr: "10.3.130.0/24"
  storage-vlan: "94"
  storage-cp-range-start: "10.3.130.30"
  storage-cp-range-end: "10.3.130.70"
  storage-dp-range-start: "10.3.130.100"
  storage-dp-range-end: "10.3.130.250"
  storage-route-dst: "192.168.22.16/28"
  storage-route-gw: "10.3.130.1"
  storage-metallb-addrpool: 10.3.130.80-10.3.130.90
  tenant-interface: "bond1.96"
  tenant-cidr: "10.1.110.0/24"
  tenant-vlan: "96"
  tenant-cp-range-start: "10.1.110.30"
  tenant-cp-range-end: "10.1.110.70"
  tenant-dp-range-start: "10.1.110.100"
  tenant-dp-range-end: "10.1.110.250"
  tenant-metallb-addrpool: 10.1.110.80-10.1.110.90
  external-interface: "bond1"
  external-cidr: "192.168.22.128/25"
  external-gw: "192.168.22.129"
  external-vlan: "1022"
  external-cp-range-start: "192.168.22.170"
  external-cp-range-end: "192.168.22.179"
  external-dp-range-start: "192.168.22.132"
  external-dp-range-end: "192.168.22.139"
  internalapi-vip: 10.2.120.80
  rabbitmq-vip: 10.2.120.85
  rabbitmq-cell1-vip: 10.2.120.86
  ctlplane-vip: 10.62.62.80
  neutron-net-vlan-ranges: "sriov1,sriov2,dpdkdata1"
  sriov-host-mem: "4096"
  sriov-0-hugepages: "4"
  sriov-1-hugepages: "4"
  sriov-cpu-shared: "2-25,66-69"
  sriov-cpu-dedicated: "6-63,70-127"
  sriov-bond0-port1: eno12399
  sriov-bond0-port2: eno12409
  sriov-physnets: "sriov1,sriov2"
  sriov-physnet1: sriov1
  sriov-physnet1-address: 0000:1f:00.2
  sriov-physnet1-port: eno12419
  sriov-physnet1-numvfs: "8"
  sriov-physnet2: sriov2
  sriov-physnet2-address: 0000:1f:00.3
  sriov-physnet2-port: eno12429
  sriov-physnet2-numvfs: "8"
  dpdk-host-mem: "8192"
  dpdk-socket-mem: "8192:8192"
  dpdk-0-hugepages: "8"
  dpdk-1-hugepages: "8"
  dpdk-cpu-shared: "0-3,64-67"
  dpdk-cpu-dedicated: "12-63,76-127"
  dpdk-cpu-isolated: "4-63,68-127"
  dpdk-pmd-cores: "4,5,6,7,8,9,10,11,68,69,70,71,72,73,74,75"
  dpdk-mem-channels: "8"
  dpdk-bond0-port1: eno12399
  dpdk-bond0-port2: eno12409
  dpdk-physnets: dpdkdata1
  dpdk-physnet1: dpdkdata1
  dpdk-dpdkbond-port1: eno12419
  dpdk-dpdkbond-port2: eno12429
