---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: quay-config-bundle-secret
  namespace: quay-enterprise
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: $path_to_secret_vault
      metadataPolicy: None
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: quay-config-bundle-secret

