---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  name: quay-operatorgroup
  namespace: quay-enterprise
spec:
  targetNamespaces:
    - quay-enterprise
