apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .metadata.name }} # eg addresspool3
  namespace: metallb-system
  {{- if and (.metadata.annotations) (ne (index .metadata.annotations "metallb.universe.tf/address-pool") nil) }}
  annotations:
    metallb.universe.tf/address-pool: {{ .metadata.name }} # eg addresspool3
  {{- end }}
spec:
  ##############
  # Expected variation in this configuration
{{ if .spec.addresses }}
  addresses:
{{ .spec.addresses | toYaml | indent 2}}
{{ end }}
  #- 3.3.3.0/24
{{ if .spec.autoAssign }}
  autoAssign: {{ .spec.autoAssign }}
{{ end }}
{{ if .spec.avoidBuggyIPs }}
  avoidBuggyIps: {{ .spec.avoidBuggyIPs }}
{{ end }}
  ##############
