# required
# count: 1-N
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .metadata.name }} # eg addresspool3
  namespace: metallb-system
{{ if .metadata.annotations }}
  annotations:
    metallb.universe.tf/address-pool: {{ index .metadata.annotations "metallb.univers.tf/address-pool" }} # eg addresspool3
{{ end }}
spec:
  ##############
  # Expected variation in this configuration
{{ if .spec.addresses }}
  addresses:
{{ .spec.addresses | toYaml | indent 2}}
{{ end }}
  #- 3.3.3.0/24
  autoAssign: true
  ##############
