# required
# count: 1-N
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: {{ .metadata.name }}
  namespace: metallb-system
spec:
  peerAddress: {{ .spec.peerAddress }} #$ip # eg 192.168.1.2
  peerASN: {{ .spec.peerASN }} #$peerasn # eg 64501
  myASN: {{ .spec.myASN }} #$myasn # eg 64500
  routerID: {{ .spec.routerID }} #$id # eg 10.10.10.10
  bfdProfile: bfdprofile
  passwordSecret: {{ .spec.passwordSecret }}
