apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: {{ .metadata.name }} # eg bgpadvertisement-1
  namespace: metallb-system
spec:
  {{- if .spec.ipAddressPools }}
  ipAddressPools:
    {{- .spec.ipAddressPools | toYaml | nindent 4 }}
  {{- end }}
  {{- if .spec.localPref }}
  localPref: {{ .spec.localPref | toYaml }}
  {{- end }}
  {{- if .spec.nodeSelectors }}
  nodeSelectors:
    {{- .spec.nodeSelectors | toYaml | nindent 4 }}
  {{- end }}
  {{- if .spec.peers }}
  peers:
    {{- .spec.peers | toYaml | nindent 4 }}
  {{- end }}
  {{- if .spec.communities }}
  communities:
    {{- .spec.communities | toYaml | nindent 4 }}
  {{- end }}
  #communities: [ $communities ]
  # Note correlation with address pool.
  # eg:
#    - 65535:65282
  aggregationLength: 32
  aggregationLengthV6: 128
