# required ==> Note that there is no fixed content which needs comparison. Omitting...
# count: 1-N
apiVersion: v1
kind: Service
metadata:
  name: {{ .metadata.name }}
  namespace: {{ .metadata.namespace }}
{{ if .metadata.annotations }}
{{- if ne (index .metadata.annotations "metallb.universe.tf/address-pool") nil -}}
  annotations:
    metallb.universe.tf/address-pool: {{ index .metadata.annotations "metallb.universe.tf/address-pool" }}
{{end}}{{- end -}}
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: {{ .spec.selector.app }} # eg server1
  type: LoadBalancer
  loadBalancerIP: {{ .spec.loadBalancerIP }} # eg 3.3.3.5
