---
apiVersion: k8s.cni.cncf.io/v1beta1
kind: MultiNetworkPolicy
metadata:
  name: deny-all
  annotations:
    k8s.v1.cni.cncf.io/policy-for: $networkName
spec:
  podSelector:
    matchLabels:    # Define which pods are affected by this policy
      $labelKey: $labelValue
  policyTypes:
  - Ingress
  ingress: []       # Deny all ingress traffic
