---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: collector
  namespace: openshift-logging
  annotations:
    ran.openshift.io/ztp-deploy-wave: "2"
{{- if .imagePullSecrets }}
imagePullSecrets: {{ .imagePullSecrets | toYaml | nindent 0 }}
{{- end }}
{{- if .secrets }}
secrets: {{ .secrets | toYaml | nindent 0 }}
{{- end }}
