---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - esoNS.yaml
  - esoOperatorgroup.yaml
  - esoSubscription.yaml
  - esoExternalSecretsConfig.yaml
  - esoClusterSecretStore.yaml
  - esoNetworkPolicy.yaml
  - esoClusterTemplates.yaml
  - esoNodeTemplates.yaml
