# Optional
# count: 1
apiVersion: nodetopology.openshift.io/v1
kind: NUMAResourcesOperator
metadata:
  name: numaresourcesoperator
spec:
  nodeGroups:
  - config:
      # Periodic is the default setting
      infoRefreshMode: Periodic
{{ if .spec.nodeGroups }}
{{ if (index .spec.nodeGroups 0).machineConfigPoolSelector }}
    machineConfigPoolSelector:
{{ (index .spec.nodeGroups 0).machineConfigPoolSelector | toYaml | indent 6 }}
#      matchLabels:
#        # This label must match the pool(s) you want to run NUMA-aligned workloads
#        pools.operator.machineconfiguration.openshift.io/worker: ""
{{ end }}
{{ end }}
