---
apiVersion: metal3.io/v1alpha1
kind: Provisioning
metadata:
  name: provisioning-configuration
spec:
  watchAllNamespaces: true
  # some servers do not support virtual media installations
  # when the image is served using the https protocol
  {{- if .spec.disableVirtualMediaTLS }}
  disableVirtualMediaTLS: true
  {{- end }}
