apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
  name: certified-operators-disconnected
  namespace: openshift-marketplace
spec:
  image: <registry.example.com:8443>/ocp/ocp4/redhat/certified-operator-index:v4.20
  sourceType: grpc
