# Combined from the following remediations for /etc/audit/auditd.conf (all roles):
#   - rhcos4-e8-master-auditd-name-format.yaml
#   - rhcos4-e8-worker-auditd-name-format.yaml
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
        - contents:
            # The following lines are the deduplicated, combined plaintext contents from all related MachineConfig remediations.
            # #
            # # This file controls the configuration of the audit daemon
            # ##krb5_key_file = /etc/audit/audit.key
            # ##name = mydomain
            # ##tcp_client_ports = 1024-65535
            # ##tcp_listen_port = 60
            # action_mail_acct = root
            # admin_space_left = 50
            # admin_space_left_action = syslog
            # disk_error_action = single
            # disk_full_action = single
            # distribute_network = no
            # flush = incremental_async
            # freq = 50
            # krb5_principal = auditd
            # local_events = yes
            # log_file = /var/log/audit/audit.log
            # log_format = ENRICHED
            # log_group = root
            # max_log_file = 6
            # max_log_file_action = rotate
            # max_restarts = 10
            # name_format = hostname
            # num_logs = 5
            # overflow_action = syslog
            # plugin_dir = /etc/audit/plugins.d
            # priority_boost = 4
            # q_depth = 400
            # space_left = 100
            # space_left_action = email
            # tcp_client_max_idle = 0
            # tcp_listen_queue = 5
            # tcp_max_per_addr = 1
            # transport = TCP
            # use_libwrap = yes
            # verify_email = yes
            # write_logs = yes
            source: data:,%23%0A%23%20This%20file%20controls%20the%20configuration%20of%20the%20audit%20daemon%0A%23%23krb5_key_file%20%3D%20%2Fetc%2Faudit%2Faudit.key%0A%23%23name%20%3D%20mydomain%0A%23%23tcp_client_ports%20%3D%201024-65535%0A%23%23tcp_listen_port%20%3D%2060%0Aaction_mail_acct%20%3D%20root%0Aadmin_space_left%20%3D%2050%0Aadmin_space_left_action%20%3D%20syslog%0Adisk_error_action%20%3D%20single%0Adisk_full_action%20%3D%20single%0Adistribute_network%20%3D%20no%0Aflush%20%3D%20incremental_async%0Afreq%20%3D%2050%0Akrb5_principal%20%3D%20auditd%0Alocal_events%20%3D%20yes%0Alog_file%20%3D%20%2Fvar%2Flog%2Faudit%2Faudit.log%0Alog_format%20%3D%20ENRICHED%0Alog_group%20%3D%20root%0Amax_log_file%20%3D%206%0Amax_log_file_action%20%3D%20rotate%0Amax_restarts%20%3D%2010%0Aname_format%20%3D%20hostname%0Anum_logs%20%3D%205%0Aoverflow_action%20%3D%20syslog%0Aplugin_dir%20%3D%20%2Fetc%2Faudit%2Fplugins.d%0Apriority_boost%20%3D%204%0Aq_depth%20%3D%20400%0Aspace_left%20%3D%20100%0Aspace_left_action%20%3D%20email%0Atcp_client_max_idle%20%3D%200%0Atcp_listen_queue%20%3D%205%0Atcp_max_per_addr%20%3D%201%0Atransport%20%3D%20TCP%0Ause_libwrap%20%3D%20yes%0Averify_email%20%3D%20yes%0Awrite_logs%20%3D%20yes%0A
          mode: 384
          overwrite: true
          path: /etc/audit/auditd.conf
metadata:
  name: 75-auditd-combo
  labels:
    machineconfiguration.openshift.io/role: worker
