---
apiVersion: ran.openshift.io/v1alpha1
kind: ClusterGroupUpgrade
metadata:
  name: cwl-upgrade-21
  namespace: ztp-core-policies
spec:
  actions:
    afterCompletion:
      deleteClusterLabels:
        upgrade-version-4-21: ""
      deleteObjects: true
  clusters:
  - cwl-site1
  enable: true
  managedPolicies:
  - cwl-upgrade-prep-21
  - cwl-upgrade-ocp-21
  - cwl-upgrade-olm-21
  - cwl-upgrade-validate-21
  # ODF uninstall/reinstall policy pair only to be used if ODF subscription fails to upgrade
  #- cwl-upgrade-odf-uninstall-21
  #- cwl-upgrade-odf-reinstall-21
  remediationStrategy:
    maxConcurrency: 1
    timeout: 480
