---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: vewl-additions
policyDefaults:
  namespace: ztp-core-policies
  policySets: []
  placement:
    clusterSelectors:
      tnc-ver: "tnc6.1"
      vewl: "true"
  remediationAction: "inform"
policies:
  # vewl configuration
  - name: vewl-config-4.20
    policyAnnotations:
      ran.openshift.io/ztp-deploy-wave: "-10"
    manifests:
    - path: other-crs/required/VEWLVM/NNCP-Bond0-OVSbr.yaml
    - path: other-crs/required/VEWLVM/VirtualMachinesNS.yaml
      patches:
        - metadata:
            name: vewl-epa
    - path: other-crs/required/VEWLVM/CUDN-vewl.yaml

# CNV Operator
    - path: other-crs/required/CNV/CnvNS.yaml
    - path: other-crs/required/CNV/CnvOperGroup.yaml
    - path: other-crs/required/CNV/CnvSubscription.yaml    
      patches:
        - spec:
            installPlanApproval: Manual
    - path: other-crs/required/CNV/CnvHyperConverged.yaml