name: Shell Format Check

on:
  pull_request:
    paths:
      - '**/*.sh'
  push:
    branches:
      - main
    paths:
      - '**/*.sh'

jobs:
  shfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install shfmt
        run: |
          sudo apt-get update
          sudo apt-get install -y shfmt
          
      - name: Run shfmt check
        run: |
          find . -type f -name '*.sh' -print0 | xargs -0 shfmt -d -i 2
