apiVersion: operator.openshift.io/v1
kind: Network
metadata:
  name: cluster
spec:
  defaultNetwork:
    ovnKubernetesConfig:
      gatewayConfig:
        routingViaHost: true
        {{ if hasKey .spec.defaultNetwork.ovnKubernetesConfig.gatewayConfig "ipForwarding" }}
        ipForwarding: Restricted
        {{ end }}
{{- $eip := .spec.defaultNetwork.ovnKubernetesConfig.egressIPConfig }}
{{- if and $eip $eip.reachabilityTotalTimeoutSeconds }}
      egressIPConfig:
        reachabilityTotalTimeoutSeconds: 1
{{- else }}
      egressIPConfig: {}
{{- end }}
  {{ if hasKey .spec "useMultiNetworkPolicy" }}
  useMultiNetworkPolicy: {{ .spec.useMultiNetworkPolicy }}
  {{ end }}
