apiVersion: operator.openshift.io/v1
kind: Network
metadata:
  name: cluster
spec:
  defaultNetwork:
    ovnKubernetesConfig:
      gatewayConfig:
        routingViaHost: true
  {{ if hasKey .spec "useMultiNetworkPolicy" }}
  useMultiNetworkPolicy: {{ .spec.useMultiNetworkPolicy }}
  {{ end }}
