# optional
# count: 1
---
apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: sizing-master
spec:
  kubeletConfig:
    # This configuration value should be tailored for each environment.
    systemReserved:
      memory: "30Gi"
  machineConfigPoolSelector:
    matchLabels:
      pools.operator.machineconfiguration.openshift.io/master: ""
